# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('Audio_server', src, depend = ['AUDIO_DECODER_DSF'], CPPPATH = CPPPATH)

Return('group')
