# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()

src  = Glob('*.c')
CPPPATH = [cwd] + [cwd + '/include']
LOCAL_CCFLAGS = ' -D_HIFI_APE_DEC -DA_CORE_DECODE'

group = DefineGroup('Audio_server', src, depend = ['AUDIO_DECODER_APE'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
